name: Check multiple toolchains

on:
  pull_request:
    types: [ labeled ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-toolchains:
    if: ${{ github.event.label.name == 'ready-to-merge' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-toolchain: [stable, nightly]
    steps:
    - uses: actions/checkout@v2
    - name: Install ${{ matrix.rust-toolchain }} toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust-toolchain }}
    - name: Run cargo check
      if: matrix.rust-toolchain != "allocator_api"
      run: cargo check --all
    - name: Run cargo check
      if: matrix.rust-toolchain == "allocator_api"
      run: cargo +nightly check --all --features="allocator_api"

